version: '3.8'
services:
  keylime-registrar:
    build:
      context: ./docker/fedora/
      dockerfile: keylime_py.Dockerfile
    image: keylime_py
    hostname: keylime-registrar
    container_name: keylime-registrar
    user: root
    network_mode: host
    volumes:
      - /var/lib/keylime:/var/lib/keylime
    ports:
      - "8891:8891"
      - "8890:8890"
    command: ["/root/wait.sh", "/var/lib/keylime/cv_ca/client-cert.crt", "keylime_registrar"]
    depends_on:
      - keylime-verifier
    environment:
      KEYLIME_REGISTRAR_IP: "0.0.0.0"