version: '3.6'
services:
  keylime-verifier:
    build:
      context: ./docker/fedora/
      dockerfile: keylime_py.Dockerfile
    image: keylime_py
    hostname: 'keylime-verifier'
    user: root
    volumes:
      - secure-volume:/var/lib/keylime
      - debug-volume:/etc
    ports:
        - "8892:8892"
    command: [
      "/usr/local/bin/keylime_verifier"
    ]
  keylime-registrar:
    build:
      context: ./docker/fedora/
      dockerfile: keylime_py.Dockerfile
    image: keylime_py
    hostname: 'keylime-registrar'
    user: root
    volumes:
      - secure-volume:/var/lib/keylime
      - debug-volume:/etc
    ports:
        - "8891:8891"
        - "8890:8890"
    command: ["/root/wait.sh", "/var/lib/keylime/cv_ca/client-cert.crt", "keylime_registrar"]
    depends_on:
      - keylime-verifier
    environment:
      KEYLIME_REGISTRAR_IP: "0.0.0.0"
  keylime-agent:
    build:
      context: ./docker/fedora/
      dockerfile: keylime_rust.Dockerfile
    image: keylime_rust
    hostname: 'keylime-agent'
    user: root
    volumes:
      - secure-volume:/var/lib/keylime
      - /sys/kernel/security/:/sys/kernel/security/
    network_mode: host
    depends_on:
      - keylime-verifier
    cap_add:
      - SETUID
      - SETGID
    environment:
    - TCTI=tabrmd:bus_type=system
    command:
      - /bin/bash
      - -c
      - |
        chmod 111 /root/wait_for_registrar.sh
        /root/wait_for_registrar.sh
        mkdir /tmp/tpmdir
        rm -rf /var/run/dbus
        mkdir /var/run/dbus
        dbus-daemon --system
        ls /etc/dbus-1/system.d/
        swtpm_setup --tpm2 \
            --tpmstate /tmp/tpmdir \
            --createek --decryption --create-ek-cert \
            --create-platform-cert \
            --display
        swtpm socket --tpm2 \
            --tpmstate dir=/tmp/tpmdir \
            --flags startup-clear \
            --ctrl type=tcp,port=2322 \
            --server type=tcp,port=2321 \
            --daemon
        tpm2-abrmd \
            --logger=stdout \
            --tcti=swtpm: \
            --allow-root \
            --flush-all &
        echo "Ensuring /var/lib/keylime/secure exists..."
        mkdir -p /var/lib/keylime/secure
        echo "Attempting to mount tmpfs..."
        mount -t tmpfs tmpfs /var/lib/keylime/secure && echo "Mounted tmpfs successfully." || echo "Failed to mount tmpfs."
        id -u keylime &>/dev/null || useradd -m keylime
        chown -R keylime:keylime /var/lib/keylime
        RUST_LOG=keylime_agent=trace /usr/bin/keylime_agent &
        tail -f /dev/null
volumes:
  secure-volume:
  debug-volume:
