version: '3.8'
services:
  keylime-verifier:
    build:
      context: ./docker/fedora/
      dockerfile: keylime_py.Dockerfile
    image: keylime_py
    hostname: keylime-verifier
    container_name: keylime-verifier
    user: root
    network_mode: host
    volumes:
      - /var/lib/keylime:/var/lib/keylime
    ports:
      - "8892:8892"
    command: [
      "/usr/local/bin/keylime_verifier"
    ]