version: '3.8'
services:
  keylime-verifier:
    build:
      context: ./docker/fedora/
      dockerfile: keylime_py.Dockerfile
    image: keylime_py
    container_name: keylime-verifier
    user: root
    network_mode: host
    volumes:
      - secure-volume:/var/lib/keylime
    ports:
      - "8892:8892"
    command: [
      "/usr/local/bin/keylime_verifier"
    ]
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.verifier-node == true
    environment:
      KEYLIME_TENANT_REQUIRE_EK_CERT: "False"
  keylime-registrar:
    build:
      context: ./docker/fedora/
      dockerfile: keylime_py.Dockerfile
    image: keylime_py
    container_name: keylime-registrar
    user: root
    network_mode: host
    volumes:
      - secure-volume:/var/lib/keylime
    ports:
      - "8891:8891"
      - "8890:8890"
    command: ["/root/wait.sh", "/var/lib/keylime/cv_ca/client-cert.crt", "keylime_registrar"]
    depends_on:
      - keylime-verifier
    environment:
      KEYLIME_REGISTRAR_IP: "0.0.0.0"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.registrar-node == true
  keylime-agent:
    build:
      context: ./docker/fedora/
      dockerfile: keylime_rust.Dockerfile
    image: keylime_rust
    container_name: keylime-agent
    user: root
    network_mode: host
    depends_on:
      - keylime-verifier
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/tpm0:/dev/tpm0
      - /dev/tpmrm0:/dev/tpmrm0
    # debug purpose, need to delete 'secure-volume' here
    # share of 'security' may not be neccessary
    volumes:
      - /sys/kernel/security/:/sys/kernel/security/
      - secure-volume:/var/lib/keylime
    environment:
      - TCTI=tabrmd:bus_type=system
    command:
      - /bin/bash
      - -c
      - |
        sleep 6
        chmod 666 /dev/tpm0
        mkdir /tmp/tpmdir
        rm -rf /var/run/dbus
        mkdir /var/run/dbus
        dbus-daemon --system
        tpm2-abrmd \
        --logger=stdout \
        --allow-root \
        --flush-all &
        mkdir /var/lib/keylime
        id -u keylime &>/dev/null || useradd -m keylime
        chown -R keylime:keylime /var/lib/keylime
        RUST_LOG=keylime_agent=trace /usr/bin/keylime_agent
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.agent-node == true
volumes:
  secure-volume:
