version: '3.8'
services:
  keylime-agent:
    build:
      context: ./docker/fedora/
      dockerfile: keylime_rust.Dockerfile
    image: keylime_rust
    hostname: keylime-agent
    container_name: keylime-agent
    user: root
    network_mode: host
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/tpm0:/dev/tpm0
      - /dev/tpmrm0:/dev/tpmrm0
    # debug purpose, need to delete 'secure-volume' here
    # share of 'security' may not be neccessary
    volumes:
      - /sys/kernel/security/:/sys/kernel/security/
      - /var/lib/keylime:/var/lib/keylime
    environment:
      - TCTI=tabrmd:bus_type=system
    command:
      - /bin/bash
      - -c
      - |
        chmod 666 /dev/tpm0
        mkdir /tmp/tpmdir
        rm -rf /var/run/dbus
        mkdir /var/run/dbus
        dbus-daemon --system
        tpm2-abrmd \
        --logger=stdout \
        --allow-root \
        --flush-all &
        mkdir /var/lib/keylime
        id -u keylime &>/dev/null || useradd -m keylime
        chown -R keylime:keylime /var/lib/keylime
        RUST_LOG=keylime_agent=trace /usr/bin/keylime_agent